<?php

namespace Arkounay\BlockI18nBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageBlockRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class PageBlockRepository extends EntityRepository
{

    public function findBySearch($search, $locale)
    {
        return $this->createQueryBuilder('block')
            ->innerJoin('Arkounay:PageBlockTranslation', 'blockTranslation', 'WITH', 'blockTranslation.translatable = block.id')
            ->where('blockTranslation.locale = :locale')
            ->andWhere('blockTranslation.contenu LIKE :search')
            ->setParameter('search', '%' . $search . '%')
            ->setParameter('locale', $locale)
            ->getQuery()->getResult();

    }

}
